model:

  device: null # "cuda" | "cpu" | "auto"

  name: "Wan2.2-TI2V-5B"
  base:
    load_from: "local" # "huggingface" | "local"
    id: "Wan-AI/Wan2.2-TI2V-5B" #FIXME: 改为本地路径加载 而非huggingface下载 即仅使用base_model_path
    dir: "./weights/WAN"

    dit: "diffusion_pytorch_model*.safetensors"
    t5: "models_t5_umt5-xxl-enc-bf16.pth"
    vae: "Wan2.2_VAE.pth"
    tokenizer: null

  dtype: "bf16"
  device: "cuda"
  # freeze_base: true  默认
  gradient_checkpointing: true

  wan:
    # model_type: "ti2v"
    patch_size: [1, 2, 2]
    vae_temporal_stride: 4
    vae_spatial_stride: 16
    # require_num_frames_4n_plus_1: true

  target:
    height: 480
    width: 832
    num_frames: 81
    hw_multiple: 32

  reference:
    # enabled: true
    image_size: 480
    # resize_mode: "center_crop_resize" 
    # encode_with_wan_vae: true
    # latent_frames: 1
    detach_latent: true   # NOTE: 也是默认的 肯定不会把梯度传latent本身上面 
    timestep: 0.0
    injection_mode: "branch_attention"   # branch_attention NOTE: 仅表明OminiControl的架构 此cfg变量不会被使用 除了未来的消融实验
    
    position:
      mode: "spatial_offset" # spatial_offset | temporal_offset  TODO: 需要针对这两种方式进行消融实验 原始OminiControl的实现是spatial_offset
      temporal_offset: 0
      h_offset: 0
      w_offset: -15

    # update_reference_branch: true   NOTE: 暂时默认为True 
    # independent_reference: false
    kv_cache_reference: true   #NOTE: 仅在inference使用 training中暂不使用

  lora:
    enabled: true
    base_model: "dit"
    target_modules: ["q", "k", "v", "o", "ffn.0", "ffn.2"]
    rank: 32
    alpha: 32
    dropout: 0.0
    init: "kaiming_zero"
    # branch_routing:
    #   target: "default"
    #   reference: "default"
    #   text: null

  text: # 基本上是用于T5 caption embedding
    max_text_len: 512
    # allow_prompt: true
    # allow_prompt_embeds: true

  inference:
    num_inference_steps: 50
    cfg_scale: 5.0 
    reference_guidance_scale: 1.0
    seed: null
    output_type: "video_tensor" # frames: list of PIL frames | video_tensor: torch.Tensor [81, 3, 480, 832] [T, C, H, W]

  training:
    prediction_type: "velocity"  # 预测类型 "noise"(WAN默认) | "velocity"  
    timestep_sampling: "logit_normal"  # 时间步采样使用正态分布    "uniform" | "logit_normal"
    loss_type: "mse"
    ref_dropout_prob: 0.05
    text_dropout_prob: 0.10