# 使用井号键"#"的参数不需要使用 现阶段暂时先注释保留

model:
  name: "FACET-WAN2.1-VACE"
  base: # 现阶段明确使用1.3B模型
    load_from: "local" # "huggingface" | "local" 
    id: "Wan-AI/Wan2.1-VACE-1.3B" # "Wan-AI/Wan2.1-VACE-1.3B" | "Wan-AI/Wan2.1-VACE-14B" 
    # 目前先针对更小的1.3B模型进行大量ablation实验 后期在14B模型上进行验证
    # "Wan2.2-VACE-Fun-A14B"将来用于架构切换后的验证 以及大容量模型的scale-up验证
    dir: "./weights/WAN2.1"

    dit: "diffusion_pytorch_model*.safetensors" #1.3B模型只有1个权重分片 14B模型有13个分片
    t5: "models_t5_umt5-xxl-enc-bf16.pth"
    vae: "Wan2.1_VAE.pth"
    # 14B模型的 text encoder & VAE 权重并非.pth 而是权重文件夹
    tokenizer: "google/umt5-xxl"

  dtype: "bf16"
  device: "cuda"  # "cuda" | "cpu" | "auto"
  gradient_checkpointing: true

  wan:
    model_type: "vace" # "ti2v" | "vace"
    patch_size: [1, 2, 2]
    vae_temporal_stride: 4
    vae_spatial_stride: 8  # Wan2.1_VACE: 8 | Wan2.2_TI2V: 16
    token_temporal_stride: 4  # 1 * 4 = 4
    token_spatial_stride: 16  # 2 * 8 = 16
    # vace_temporal_stride: 4
    # vace_spatial_stride: 16

  target:
    height: 480
    width: 832
    num_frames: 81
    hw_multiple: 32

  reference:
    image_size: 480
    # latent_frames: 1
    f_offset: 21  # 计算RoPE时临时将reference image放置在latent token的右侧 即第22个token的位置
    detach_latent: true   # NOTE: 也是默认的 肯定不会把梯度传latent本身上面 
    timestep: 0.0   # 设置ref branch的加噪步为0 告知模型此为干净图像 而非噪声 
    injection_mode: "branch_attention"   # branch_attention NOTE: 仅表明OminiControl的架构 此cfg变量不会被使用 除了未来的消融实验
    # update_reference_branch: true   NOTE: 暂时默认为True 代表ref token在forward过程中自身也要产生变化
    kv_cache_reference: true   #NOTE: 仅在inference使用 training中暂不使用

  lora:
    # enabled: true
    # base_model: "dit"
    target_modules: ["q", "k", "v", "o", "ffn.0", "ffn.2"]
    on_base_blocks: True  # 对于WAN DiT blocks注入LoRA参数
    on_vace_blocks: True  # 对于VaceWanBlock注入LoRA参数
    rank: 32     # 沿用 DiffSynth 的设置
    alpha: 32
    dropout: 0.0
    init: "kaiming_zero"
    # branch_routing: 现阶段暂时不使用

  text: # text / caption embedding
    max_text_len: 512

  inference:
    num_inference_steps: 50
    cfg_scale: 5.0 
    reference_guidance_scale: 1.0
    seed: null
    output_type: "video" # frames: list of PIL frames | video: torch.Tensor [81, 3, 480, 832] [T, C, H, W]

  training:
    prediction_type: "velocity"  # 预测类型 "noise"(WAN默认) | "velocity"  
    timestep_sampling: "logit_normal"  # 时间步采样使用正态分布    "uniform" | "logit_normal"
    loss_type: "mse"
    ref_dropout_prob: 0.05
    text_dropout_prob: 0.10